added dependency check for find-tokens

diff --git a/comango b/comango
--- a/comango
+++ b/comango
@@ -37,6 +37,12 @@ test -z $git_url     && echo "git_url not set"     && exit 1
 test -z $base_repo   && echo "base_repo not set"   && exit 1
 test -z $repo_prefix && echo "repo_prefix not set" && exit 1
 
+# check if find-tokens is in path
+which find-tokens &> /dev/null
+if [ "$?" == 1 ]; then
+  echo "${red}find-tokens dependency is missing${reset}"
+  exit 1
+fi
 
 mkdir -p $REPOS_DIR $BUILD_DIR
 
